In [1]:
import numpy as np

In [3]:
# 1. Buatlah Data Array Integer dr 10 s/d 50
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
# 2. Buatlah Data array integer 10 s/d 50 kelipatan 2
newArr = np.arange(10, 50, 2)
newArr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [7]:
# 3. Buatlah Array 3x3 dr 0-8
array = np.arange(0,9)
shapeArray = array.reshape(3,3)
shapeArray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# 4. Buatlah data array random dengan nilai 25
randArr = np.random.randn(25)
randArr

array([-0.27431556,  1.21695292, -2.30608827,  2.11141679,  0.36747188,
        1.44946863,  0.76648742, -0.9883005 ,  2.5328332 ,  0.47360523,
       -0.13288824, -0.24812753,  0.39903443, -0.88311577,  1.29785104,
        2.0022605 ,  0.11067252,  0.59240192, -1.50175969,  0.52156867,
        1.02244438,  0.72632433,  1.52492376,  0.16168376, -0.98426921])

In [11]:
# 5. Buatlah data array 5x5 1-25
arrayMulti = np.arange(1,26)
newArrayMulti = arrayMulti.reshape(5,5)
newArrayMulti

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
# 6. Menampilkan array
newArrayMulti[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [13]:
# 7. Tampilkan angka 20
newArrayMulti[3, 4]

20

In [37]:
# 8. Tampilkan Array seperti ini
newArrayMulti[3:, 4:]

array([[20],
       [25]])

In [16]:
# 9. Tampilkan Max, min, argmax, argmin
print('ini max : ', newArrayMulti.max())
print('ini min : ', newArrayMulti.min())
print('ini argmax : ', newArrayMulti.argmax())
print('ini argmin : ', newArrayMulti.argmin())

ini max :  25
ini min :  1
ini argmax :  24
ini argmin :  0


In [41]:
# 10. Tampilkan nilai array > 10 && <=20
arrayMulti[10:20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])